import type { Question, WordEntry, WordProgress } from '../types';
const r=<T,>(a:T[])=>a[Math.floor(Math.random()*a.length)];
export const getDistractors=(word:WordEntry,all:WordEntry,count=3)=>all.filter(w=>w.id!==word.id&&w.pos===word.pos).slice(0,20).sort(()=>Math.random()-0.5).slice(0,count);
export const generateMeaningQuestion=(w:WordEntry,a:WordEntry[]):Question=>({id:crypto.randomUUID(),wordId:w.id,type:'meaning',prompt:`${w.word} 的中文意思是？`,options:[w.meaning_cn,...getDistractors(w,a).map(x=>x.meaning_cn)].sort(()=>Math.random()-0.5),answer:w.meaning_cn});
export const generateRecallQuestion=(w:WordEntry,a:WordEntry[]):Question=>({id:crypto.randomUUID(),wordId:w.id,type:'recall',prompt:`哪个英文词对应：${w.meaning_cn}？`,options:[w.word,...getDistractors(w,a).map(x=>x.word)].sort(()=>Math.random()-0.5),answer:w.word});
export const generateContextQuestion=(w:WordEntry,a:WordEntry[]):Question=>({id:crypto.randomUUID(),wordId:w.id,type:'context',prompt:w.example.replace(new RegExp(w.word,'ig'),'_____'),options:[w.word,...getDistractors(w,a).map(x=>x.word)].sort(()=>Math.random()-0.5),answer:w.word});
export const generateSpellingQuestion=(w:WordEntry):Question=>({id:crypto.randomUUID(),wordId:w.id,type:'spelling',prompt:`拼写：${w.meaning_cn}（首字母 ${w.word[0]}）`,answer:w.word});
export const generateSynonymQuestion=(w:WordEntry,a:WordEntry[]):Question=>({id:crypto.randomUUID(),wordId:w.id,type:'synonym',prompt:`${w.word} 的近义词是？`,options:[w.synonyms[0],...getDistractors(w,a).map(x=>x.synonyms[0]||x.word)].sort(()=>Math.random()-0.5),answer:w.synonyms[0]});
export const generateQuestion=(w:WordEntry,all:WordEntry,progress:WordProgress|undefined,mode:'daily'|'shadow'|'trial'):Question=>{const s=progress?.status??'new';if(mode==='shadow')return Math.random()>0.5?generateSpellingQuestion(w):generateRecallQuestion(w,all);if(s==='new')return Math.random()>0.5?generateMeaningQuestion(w,all):generateContextQuestion(w,all);if(s==='weak')return Math.random()>0.5?generateSpellingQuestion(w):generateRecallQuestion(w,all);if((s==='familiar'||s==='mastered')&&w.synonyms.length&&Math.random()>0.7)return generateSynonymQuestion(w,all);return r([generateMeaningQuestion(w,all),generateRecallQuestion(w,all),generateContextQuestion(w,all)]);};
