import { useMemo, useState } from 'react';
import { wordBank } from './data/wordBank';
import { loadState, saveState, resetState } from './utils/storage';
import { calculateLevel, createSessionRecord, getDailyQueue, getNextLevelXp, getProficiencyBonus } from './utils/gameLogic';
import { generateQuestion } from './utils/questionGenerator';
import { createWordProgress } from './utils/wordProgress';
export default function App(){const [state,setState]=useState(loadState());const [session,setSession]=useState<any>(null);const level=calculateLevel(state.userProfile.xp);
const queue=useMemo(()=>getDailyQueue(wordBank,state.wordProgress),[state.wordProgress]);
const start=()=>setSession({idx:0,items:queue,record:createSessionRecord('daily'),answer:'',feedback:null});
const current=session?.items[session.idx];const q=current?generateQuestion(current,wordBank,state.wordProgress[current.id],'daily'):null;
const submit=(ans:string)=>{if(!q||!current)return;const correct=ans.trim().toLowerCase()===q.answer.trim().toLowerCase();const wp=state.wordProgress[current.id]??createWordProgress(current.id);const nwp={...wp,timesSeen:wp.timesSeen+1,timesCorrect:wp.timesCorrect+(correct?1:0),status:correct?'learning':'weak',mastery:Math.max(0,Math.min(5,wp.mastery+(correct?1:-1))),wrongCount:wp.wrongCount+(correct?0:1),streakCorrect:correct?wp.streakCorrect+1:0,questionStats:wp.questionStats};const ns={...state,wordProgress:{...state.wordProgress,[current.id]:nwp},userProfile:{...state.userProfile,xp:state.userProfile.xp+(correct?3:1)}};setState(ns);saveState(ns);setSession({...session,feedback:{correct,ans:q.answer}})};
if(session&&session.idx>=session.items.length)return <div className='p-6'><h1>Session Complete</h1><button onClick={()=>setSession(null)}>Back</button></div>
return <div className='max-w-6xl mx-auto p-4 grid gap-4 md:grid-cols-[240px_1fr]'><aside className='card'><h1 className='text-xl text-arcane-accent'>IELTS Arcane Sheet</h1><p>Lv {level} XP {state.userProfile.xp}/{getNextLevelXp(level)}</p><p>PB +{getProficiencyBonus(level)}</p><button className='mt-2 px-3 py-1 bg-arcane-accent text-black rounded' onClick={start}>Start Daily</button><button className='mt-2 ml-2 px-3 py-1 border rounded' onClick={()=>{resetState();location.reload();}}>Reset</button></aside><main className='space-y-4'>{!session?<div className='card'><p>Daily queue: {queue.length}</p><p>Demo words: {wordBank.length}</p></div>:<div className='card'><p>{session.idx+1}/{session.items.length}</p><p>{q?.prompt}</p>{q?.options?<div className='grid gap-2'>{q.options.map(o=><button className='border rounded p-2' onClick={()=>submit(o)} key={o}>{o}</button>)}</div>:<input className='bg-slate-900 p-2 rounded' onKeyDown={e=>{if(e.key==='Enter')submit((e.target as HTMLInputElement).value)}}/>}{session.feedback&&<div><p>{session.feedback.correct?'Correct':'Incorrect'} → {session.feedback.ans}</p><button onClick={()=>setSession({...session,idx:session.idx+1,feedback:null})}>Next</button></div>}</div>}</main></div>}
